# Generated by Django 3.0.3 on 2020-03-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('option', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
