# Generated by Django 3.0.3 on 2020-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20200302_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='optionPerm',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
