# Generated by Django 3.0.3 on 2020-03-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20200308_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authApp.Task')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authApp.User')),
            ],
        ),
    ]
